### ISSUE TITLE
Добавить выгрузку текущего статуса бота на диск

### ISSUE THREAD

**Issue by Izeren** [Izeren/pewpewbot#1]
Надо написать сериализатор/десериализатор, чтобы выгружать на диск state бота например в json (можно пока не заморачиваться на синхронность)
Можно привязать к обновлению статуса по таймеру и/или к новым взятым кодам

**Comment by sVerentsov** [comment]
Коммент из #17:
Сейчас после рестарта бота нужно руками возвращать все конфиги, которые правились, хочется иметь возможность оперативно рестартить бота без необходимости перенастраивать конфиги
